services:
  db:
    image: postgres:16
    environment:
      POSTGRES_USER: padel
      POSTGRES_PASSWORD: padel_secret
      POSTGRES_DB: padeltracker
    volumes:
      - db-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "padel"]
      interval: 5s
      timeout: 3s
      retries: 5
    restart: unless-stopped

  backend:
    build: ./backend
    environment:
      DATABASE_URL: postgres://padel:padel_secret@db:5432/padeltracker
      PORT: 4000
    ports:
      - "4000:4000"
    depends_on:
      - db
    restart: unless-stopped

  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend
    restart: unless-stopped

volumes:
  db-data:
